name: Deploy to Supabase
on:
  push:
    branches: [main]
    # Only run when there are changes to migration files
    paths:
      - "supabase/migrations/**"
      - "supabase/config.toml"

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # You can create this environment in GitHub settings

    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: |
          supabase link --project-ref $PROJECT_ID

      - name: Push database migrations
        run: |
          supabase db push

      - name: Verify migration success
        run: |
          echo "✅ Database migrations pushed successfully to production"
