name: Storybook Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  storybook-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
    
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test-storybook
    
    - name: Upload Storybook build artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: storybook-static
        path: storybook-static/
        retention-days: 30